export const SESSION_SAVE = 'SESSION_SAVE';
export const SESSION_CLEAR = 'SESSION_CLEAR';

export const TAGS_LOAD_REQUEST = 'TAGS_LOAD_REQUEST';
export const TAGS_LOAD_SUCCESFULL = 'TAGS_LOAD_SUCCESFULL';
export const TAGS_LOAD_FAILURE = 'TAGS_LOAD_FAILURE';

export const ADVERTS_LOAD_REQUEST = 'ADVERTS_LOAD_REQUEST';
export const ADVERTS_LOAD_SUCCESFULL = 'ADVERTS_LOAD_SUCCESFULL';
export const ADVERTS_LOAD_FAILURE = 'ADVERTS_LOAD_FAILURE';

export const ADVERTS_CREATE_REQUEST = 'ADVERTS_CREATE_REQUEST';
export const ADVERTS_CREATE_SUCCESFULL = 'ADVERTS_CREATE_SUCCESFULL';
export const ADVERTS_CREATE_FAILURE = 'ADVERTS_CREATE_FAILURE';

export const ADVERTS_UPDATE_REQUEST = 'ADVERTS_UPDATE_REQUEST';
export const ADVERTS_UPDATE_SUCCESFULL = 'ADVERTS_UPDATE_SUCCESFULL';
export const ADVERTS_UPDATE_FAILURE = 'ADVERTS_UPDATE_FAILURE';
