export const SESSION_SAVE = 'SESSION_SAVE';
export const SESSION_CLEAR = 'SESSION_CLEAR';

export const TAGS_LOAD_REQUEST = 'TAGS_LOAD_REQUEST';
export const TAGS_LOAD_SUCCESFULL = 'TAGS_LOAD_SUCCESFULL';
export const TAGS_LOAD_FAILURE = 'TAGS_LOAD_FAILURE';

export const ADVERTS_LOAD_REQUEST = 'ADVERTS_LOAD_REQUEST';
export const ADVERTS_LOAD_SUCCESFULL = 'ADVERTS_LOAD_SUCCESFULL';
export const ADVERTS_LOAD_FAILURE = 'ADVERTS_LOAD_FAILURE';
